Feat/#2123 master merge
mojaloop/central-settlement pull request #351
Opened 2021-05-13 11:44 UTC by vgenev

Added support for Default Settlement

2021-05-13 13:10 UTC, mdebarros requested changes
Please add the settlementModels[].name to the test names to be more explicit.

For example, see comment on https://github.com/mojaloop/central-settlement/pull/351/files#diff-b7daa6283e695acc3c40fd5b531a3947511767cbaac995e27107e734eee38aeeR625.

See comment about handling the error scenario when no Settlement Model is found for CGS on getSettlementModelByTransferId.

2021-05-13 13:10 UTC, mdebarros commented on test/integration/settlement_deferred_net_scenario/settlementTransfer.test.js
> +  await settlementTransferTest.test('#66 create a settlement with previous window remaining content and settle it:', async test => {
```suggestion
  await settlementTransferTest.test('#66 create a settlement with previous window remaining content and settle it using the DEFAULT_DEFERREDNET Settlement Model:', async test => {
```

2021-05-13 13:10 UTC, mdebarros commented on test/integration/settlement_deferred_net_scenario/settlementTransfer.test.js
> +    name: 'DEFERREDNET',
```suggestion
    name: 'DEFAULT_DEFERREDNET',
```

2021-05-13 15:59 UTC, vgenev commented on src/models/transferSettlement/facade.js
> +  }
the transfer remains unsettled and should be settled in DEFERREDNET settlement model (either by currency or by default model)

2021-05-14 18:07 UTC, mdebarros approved these changes
+1

2021-05-14 18:07 UTC, merged